apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: miniapi-prod
spec:
  secretName: miniapi-production-certificate
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - 35.226.164.101.nip.io
